services:
  crm-service:
    build: .
    container_name: crm-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://crm-db:5432/nexus_crm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - crm-db
      - rabbitmq

  crm-db:
    image: postgres:16
    container_name: crm-db
    environment:
      - POSTGRES_DB=nexus_crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
