server:
  port: 8083

spring:
  application:
    name: nexus-sales
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_sales
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
