server:
  port: 8083

spring:
  application:
    name: nexus-sales
  datasource:
    url: jdbc:postgresql://localhost:5434/nexus_sales
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
